### PR TITLE
Update Bump.sh description and new logo

### PR DESCRIPTION
**Pull request by ChristopheDujarric**
### Description

- Updating the Bump.sh product description
- Updating the Bump.sh logo to the new version

### CODE REVIEW

**Review by yada — APPROVED** [review]
LGTM with thanks

**Comment by yada** [comment]
@ChristopheDujarric please check the DCO check (mandatory) and I'll merge asap

**Comment by ChristopheDujarric** [comment]
@yada thank you! Now fixed 👍

**Comment by lbroudoux** [comment]
Deployment has been done on hub.microcks.io and logo and description are now updated. However, only the `APIPackage` logo has been updated - the Train Travel `APIVersion` still remains on older logo. Don't know if it's intended or not. If you want to apply the same update on Train Travel, you have to update the https://github.com/microcks/community-mocks/blob/master/artifacts/bump.sh/train-travel/1.0/train-travel.1.0.api.yml file.

**Comment by ChristopheDujarric** [comment]
Thank you! It was not intended, I'll update it right now.

**Pull request merged**
